name: Deploy Bot to Server

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug IPv6
        run: ping6 ${{ secrets.SERVER_IP }} -c 3

      - name: Copy files to server and restart bot
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/TestBot
            git pull origin master
            source venv/bin/activate
            pip3 install -r requirements.txt
            pm2 restart TestBot || pm2 start main.py --name TestBot
