name: Start Discord Test

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Load Environment Variables
        run: |
          echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" >> $GITHUB_ENV
          echo "GIT_PAT_TOKEN=${{ secrets.GIT_PAT_TOKEN }}" >> $GITHUB_ENV

      - name: Install cloudflared
        run: |
          wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb

      - name: Run bot and expose with cloudflared tunnel
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: |
          echo "Starting the bot..."
          nohup python main.py > bot.log 2>&1 &

          sleep 5

          nohup cloudflared tunnel --url http://localhost:8000 --no-autoupdate > tunnel.log 2>&1 &
          sleep 5

          echo "====================================="
          echo "🔗 ССЫЛКА НА WEB-ИНТЕРФЕЙС:"
          grep -Eo 'https://[^[:space:]]+' tunnel.log || echo "❌ Не удалось получить ссылку"
          echo "====================================="

      - name: Keep alive (чтобы не завершался)
        run: |
          echo "⏳ Поддерживаем workflow активным..."
          tail -f /dev/null
